spring:
    config:
        import: env.properties
    datasource:
        password: ${PASSWORD}
        url: jdbc:postgresql://127.0.0.1:35545/school
        username: ${DB_USER}
    flyway:
        baseline-on-migrate: true
    main:
        banner-mode: off
